// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protos/request/request.proto

package requestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeCoffeeAction_CoffeeEnum int32

const (
	MakeCoffeeAction_ESPRESSO   MakeCoffeeAction_CoffeeEnum = 0
	MakeCoffeeAction_AMERICANO  MakeCoffeeAction_CoffeeEnum = 1
	MakeCoffeeAction_CAPPUCCINO MakeCoffeeAction_CoffeeEnum = 2
	MakeCoffeeAction_LATTE      MakeCoffeeAction_CoffeeEnum = 3
	MakeCoffeeAction_CACAO      MakeCoffeeAction_CoffeeEnum = 4
	MakeCoffeeAction_SIMPLE     MakeCoffeeAction_CoffeeEnum = 5
)

// Enum value maps for MakeCoffeeAction_CoffeeEnum.
var (
	MakeCoffeeAction_CoffeeEnum_name = map[int32]string{
		0: "ESPRESSO",
		1: "AMERICANO",
		2: "CAPPUCCINO",
		3: "LATTE",
		4: "CACAO",
		5: "SIMPLE",
	}
	MakeCoffeeAction_CoffeeEnum_value = map[string]int32{
		"ESPRESSO":   0,
		"AMERICANO":  1,
		"CAPPUCCINO": 2,
		"LATTE":      3,
		"CACAO":      4,
		"SIMPLE":     5,
	}
)

func (x MakeCoffeeAction_CoffeeEnum) Enum() *MakeCoffeeAction_CoffeeEnum {
	p := new(MakeCoffeeAction_CoffeeEnum)
	*p = x
	return p
}

func (x MakeCoffeeAction_CoffeeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MakeCoffeeAction_CoffeeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_request_request_proto_enumTypes[0].Descriptor()
}

func (MakeCoffeeAction_CoffeeEnum) Type() protoreflect.EnumType {
	return &file_protos_request_request_proto_enumTypes[0]
}

func (x MakeCoffeeAction_CoffeeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MakeCoffeeAction_CoffeeEnum.Descriptor instead.
func (MakeCoffeeAction_CoffeeEnum) EnumDescriptor() ([]byte, []int) {
	return file_protos_request_request_proto_rawDescGZIP(), []int{1, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Types that are assignable to Action:
	//
	//	*Request_MakeCoffee
	Action isRequest_Action `protobuf_oneof:"Action"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_request_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_request_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (m *Request) GetAction() isRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Request) GetMakeCoffee() *MakeCoffeeAction {
	if x, ok := x.GetAction().(*Request_MakeCoffee); ok {
		return x.MakeCoffee
	}
	return nil
}

type isRequest_Action interface {
	isRequest_Action()
}

type Request_MakeCoffee struct {
	MakeCoffee *MakeCoffeeAction `protobuf:"bytes,2,opt,name=MakeCoffee,proto3,oneof"`
}

func (*Request_MakeCoffee) isRequest_Action() {}

type MakeCoffeeAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoffeeType  MakeCoffeeAction_CoffeeEnum `protobuf:"varint,1,opt,name=CoffeeType,proto3,enum=vending.MakeCoffeeAction_CoffeeEnum" json:"CoffeeType,omitempty"`
	SugarAmount uint32                      `protobuf:"varint,2,opt,name=SugarAmount,proto3" json:"SugarAmount,omitempty"`
}

func (x *MakeCoffeeAction) Reset() {
	*x = MakeCoffeeAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_request_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeCoffeeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCoffeeAction) ProtoMessage() {}

func (x *MakeCoffeeAction) ProtoReflect() protoreflect.Message {
	mi := &file_protos_request_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCoffeeAction.ProtoReflect.Descriptor instead.
func (*MakeCoffeeAction) Descriptor() ([]byte, []int) {
	return file_protos_request_request_proto_rawDescGZIP(), []int{1}
}

func (x *MakeCoffeeAction) GetCoffeeType() MakeCoffeeAction_CoffeeEnum {
	if x != nil {
		return x.CoffeeType
	}
	return MakeCoffeeAction_ESPRESSO
}

func (x *MakeCoffeeAction) GetSugarAmount() uint32 {
	if x != nil {
		return x.SugarAmount
	}
	return 0
}

var File_protos_request_request_proto protoreflect.FileDescriptor

var file_protos_request_request_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x76, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x60, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x3b, 0x0a, 0x0a, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0a, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd7, 0x01, 0x0a, 0x10, 0x4d, 0x61,
	0x6b, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x44,
	0x0a, 0x0a, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x24, 0x2e, 0x76, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x6b,
	0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x66, 0x66, 0x65, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0a, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x75, 0x67, 0x61, 0x72, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x53, 0x75, 0x67, 0x61, 0x72,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x0a, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x53, 0x50, 0x52, 0x45, 0x53, 0x53, 0x4f,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4d, 0x45, 0x52, 0x49, 0x43, 0x41, 0x4e, 0x4f, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x41, 0x50, 0x50, 0x55, 0x43, 0x43, 0x49, 0x4e, 0x4f, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x41, 0x54, 0x54, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x43, 0x41, 0x43, 0x41, 0x4f, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4d, 0x50, 0x4c,
	0x45, 0x10, 0x05, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x73, 0x75, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65,
	0x2d, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_request_request_proto_rawDescOnce sync.Once
	file_protos_request_request_proto_rawDescData = file_protos_request_request_proto_rawDesc
)

func file_protos_request_request_proto_rawDescGZIP() []byte {
	file_protos_request_request_proto_rawDescOnce.Do(func() {
		file_protos_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_request_request_proto_rawDescData)
	})
	return file_protos_request_request_proto_rawDescData
}

var file_protos_request_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_request_request_proto_goTypes = []interface{}{
	(MakeCoffeeAction_CoffeeEnum)(0), // 0: vending.MakeCoffeeAction.CoffeeEnum
	(*Request)(nil),                  // 1: vending.Request
	(*MakeCoffeeAction)(nil),         // 2: vending.MakeCoffeeAction
}
var file_protos_request_request_proto_depIdxs = []int32{
	2, // 0: vending.Request.MakeCoffee:type_name -> vending.MakeCoffeeAction
	0, // 1: vending.MakeCoffeeAction.CoffeeType:type_name -> vending.MakeCoffeeAction.CoffeeEnum
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_request_request_proto_init() }
func file_protos_request_request_proto_init() {
	if File_protos_request_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_request_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_request_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeCoffeeAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_request_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_MakeCoffee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_request_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_request_request_proto_goTypes,
		DependencyIndexes: file_protos_request_request_proto_depIdxs,
		EnumInfos:         file_protos_request_request_proto_enumTypes,
		MessageInfos:      file_protos_request_request_proto_msgTypes,
	}.Build()
	File_protos_request_request_proto = out.File
	file_protos_request_request_proto_rawDesc = nil
	file_protos_request_request_proto_goTypes = nil
	file_protos_request_request_proto_depIdxs = nil
}
