name: Go build&test flow

on:
  pull_request:
    branches: [ "trunk" ]
  push:
    paths:
      - cloud/**


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        working-directory: cloud
        run: go build -v ./...

      - name: Test
        working-directory: cloud
        run: go test -v ./...
